name: Deploy Build Atlas (Homologação)

on:
  push:
    branches:
      - main # O deploy roda sempre que você fizer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executando Deploy via SSH na VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Entra na pasta do projeto no servidor (Crie esta pasta na VPS primeiro!)
            cd /var/www/buildatlas-preview
            
            # 2. Puxa as novidades do seu repositório oficial (Você precisará ter dado um git clone lá primeiro)
            git pull origin main
            
            # 3. Derruba a versão antiga e sobe a nova com Apache
            docker compose down
            docker compose up -d
            
            echo "✅ Deploy Finalizado com Sucesso!"
